// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

package com.sparshj.proto;

public final class TransactionProtos {
  private TransactionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sparshj.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    java.lang.String getTransactionId();
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    com.google.protobuf.ByteString
        getTransactionIdBytes();

    /**
     * <code>string account_number = 2;</code>
     * @return The accountNumber.
     */
    java.lang.String getAccountNumber();
    /**
     * <code>string account_number = 2;</code>
     * @return The bytes for accountNumber.
     */
    com.google.protobuf.ByteString
        getAccountNumberBytes();

    /**
     * <code>string transaction_reference = 3;</code>
     * @return The transactionReference.
     */
    java.lang.String getTransactionReference();
    /**
     * <code>string transaction_reference = 3;</code>
     * @return The bytes for transactionReference.
     */
    com.google.protobuf.ByteString
        getTransactionReferenceBytes();

    /**
     * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
     * @return Whether the transactionDatetime field is set.
     */
    boolean hasTransactionDatetime();
    /**
     * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
     * @return The transactionDatetime.
     */
    com.google.protobuf.Timestamp getTransactionDatetime();
    /**
     * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTransactionDatetimeOrBuilder();

    /**
     * <code>double amount = 5;</code>
     * @return The amount.
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code sparshj.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sparshj.Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      transactionId_ = "";
      accountNumber_ = "";
      transactionReference_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Transaction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              transactionId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              accountNumber_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              transactionReference_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (transactionDatetime_ != null) {
                subBuilder = transactionDatetime_.toBuilder();
              }
              transactionDatetime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactionDatetime_);
                transactionDatetime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 41: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sparshj.proto.TransactionProtos.internal_static_sparshj_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sparshj.proto.TransactionProtos.internal_static_sparshj_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sparshj.proto.TransactionProtos.Transaction.class, com.sparshj.proto.TransactionProtos.Transaction.Builder.class);
    }

    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object transactionId_;
    /**
     * <code>string transaction_id = 1;</code>
     * @return The transactionId.
     */
    @java.lang.Override
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      }
    }
    /**
     * <code>string transaction_id = 1;</code>
     * @return The bytes for transactionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_NUMBER_FIELD_NUMBER = 2;
    private volatile java.lang.Object accountNumber_;
    /**
     * <code>string account_number = 2;</code>
     * @return The accountNumber.
     */
    @java.lang.Override
    public java.lang.String getAccountNumber() {
      java.lang.Object ref = accountNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string account_number = 2;</code>
     * @return The bytes for accountNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountNumberBytes() {
      java.lang.Object ref = accountNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTION_REFERENCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object transactionReference_;
    /**
     * <code>string transaction_reference = 3;</code>
     * @return The transactionReference.
     */
    @java.lang.Override
    public java.lang.String getTransactionReference() {
      java.lang.Object ref = transactionReference_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionReference_ = s;
        return s;
      }
    }
    /**
     * <code>string transaction_reference = 3;</code>
     * @return The bytes for transactionReference.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTransactionReferenceBytes() {
      java.lang.Object ref = transactionReference_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTION_DATETIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp transactionDatetime_;
    /**
     * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
     * @return Whether the transactionDatetime field is set.
     */
    @java.lang.Override
    public boolean hasTransactionDatetime() {
      return transactionDatetime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
     * @return The transactionDatetime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTransactionDatetime() {
      return transactionDatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : transactionDatetime_;
    }
    /**
     * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTransactionDatetimeOrBuilder() {
      return getTransactionDatetime();
    }

    public static final int AMOUNT_FIELD_NUMBER = 5;
    private double amount_;
    /**
     * <code>double amount = 5;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTransactionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transactionId_);
      }
      if (!getAccountNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountNumber_);
      }
      if (!getTransactionReferenceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, transactionReference_);
      }
      if (transactionDatetime_ != null) {
        output.writeMessage(4, getTransactionDatetime());
      }
      if (amount_ != 0D) {
        output.writeDouble(5, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTransactionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transactionId_);
      }
      if (!getAccountNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountNumber_);
      }
      if (!getTransactionReferenceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, transactionReference_);
      }
      if (transactionDatetime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTransactionDatetime());
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sparshj.proto.TransactionProtos.Transaction)) {
        return super.equals(obj);
      }
      com.sparshj.proto.TransactionProtos.Transaction other = (com.sparshj.proto.TransactionProtos.Transaction) obj;

      if (!getTransactionId()
          .equals(other.getTransactionId())) return false;
      if (!getAccountNumber()
          .equals(other.getAccountNumber())) return false;
      if (!getTransactionReference()
          .equals(other.getTransactionReference())) return false;
      if (hasTransactionDatetime() != other.hasTransactionDatetime()) return false;
      if (hasTransactionDatetime()) {
        if (!getTransactionDatetime()
            .equals(other.getTransactionDatetime())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionId().hashCode();
      hash = (37 * hash) + ACCOUNT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getAccountNumber().hashCode();
      hash = (37 * hash) + TRANSACTION_REFERENCE_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionReference().hashCode();
      if (hasTransactionDatetime()) {
        hash = (37 * hash) + TRANSACTION_DATETIME_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionDatetime().hashCode();
      }
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sparshj.proto.TransactionProtos.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sparshj.proto.TransactionProtos.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sparshj.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sparshj.Transaction)
        com.sparshj.proto.TransactionProtos.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sparshj.proto.TransactionProtos.internal_static_sparshj_Transaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sparshj.proto.TransactionProtos.internal_static_sparshj_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sparshj.proto.TransactionProtos.Transaction.class, com.sparshj.proto.TransactionProtos.Transaction.Builder.class);
      }

      // Construct using com.sparshj.proto.TransactionProtos.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        transactionId_ = "";

        accountNumber_ = "";

        transactionReference_ = "";

        if (transactionDatetimeBuilder_ == null) {
          transactionDatetime_ = null;
        } else {
          transactionDatetime_ = null;
          transactionDatetimeBuilder_ = null;
        }
        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sparshj.proto.TransactionProtos.internal_static_sparshj_Transaction_descriptor;
      }

      @java.lang.Override
      public com.sparshj.proto.TransactionProtos.Transaction getDefaultInstanceForType() {
        return com.sparshj.proto.TransactionProtos.Transaction.getDefaultInstance();
      }

      @java.lang.Override
      public com.sparshj.proto.TransactionProtos.Transaction build() {
        com.sparshj.proto.TransactionProtos.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sparshj.proto.TransactionProtos.Transaction buildPartial() {
        com.sparshj.proto.TransactionProtos.Transaction result = new com.sparshj.proto.TransactionProtos.Transaction(this);
        result.transactionId_ = transactionId_;
        result.accountNumber_ = accountNumber_;
        result.transactionReference_ = transactionReference_;
        if (transactionDatetimeBuilder_ == null) {
          result.transactionDatetime_ = transactionDatetime_;
        } else {
          result.transactionDatetime_ = transactionDatetimeBuilder_.build();
        }
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sparshj.proto.TransactionProtos.Transaction) {
          return mergeFrom((com.sparshj.proto.TransactionProtos.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sparshj.proto.TransactionProtos.Transaction other) {
        if (other == com.sparshj.proto.TransactionProtos.Transaction.getDefaultInstance()) return this;
        if (!other.getTransactionId().isEmpty()) {
          transactionId_ = other.transactionId_;
          onChanged();
        }
        if (!other.getAccountNumber().isEmpty()) {
          accountNumber_ = other.accountNumber_;
          onChanged();
        }
        if (!other.getTransactionReference().isEmpty()) {
          transactionReference_ = other.transactionReference_;
          onChanged();
        }
        if (other.hasTransactionDatetime()) {
          mergeTransactionDatetime(other.getTransactionDatetime());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sparshj.proto.TransactionProtos.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sparshj.proto.TransactionProtos.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object transactionId_ = "";
      /**
       * <code>string transaction_id = 1;</code>
       * @return The transactionId.
       */
      public java.lang.String getTransactionId() {
        java.lang.Object ref = transactionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transactionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @return The bytes for transactionId.
       */
      public com.google.protobuf.ByteString
          getTransactionIdBytes() {
        java.lang.Object ref = transactionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @param value The transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transactionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionId() {
        
        transactionId_ = getDefaultInstance().getTransactionId();
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_id = 1;</code>
       * @param value The bytes for transactionId to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transactionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accountNumber_ = "";
      /**
       * <code>string account_number = 2;</code>
       * @return The accountNumber.
       */
      public java.lang.String getAccountNumber() {
        java.lang.Object ref = accountNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account_number = 2;</code>
       * @return The bytes for accountNumber.
       */
      public com.google.protobuf.ByteString
          getAccountNumberBytes() {
        java.lang.Object ref = accountNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account_number = 2;</code>
       * @param value The accountNumber to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountNumber() {
        
        accountNumber_ = getDefaultInstance().getAccountNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string account_number = 2;</code>
       * @param value The bytes for accountNumber to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transactionReference_ = "";
      /**
       * <code>string transaction_reference = 3;</code>
       * @return The transactionReference.
       */
      public java.lang.String getTransactionReference() {
        java.lang.Object ref = transactionReference_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transactionReference_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string transaction_reference = 3;</code>
       * @return The bytes for transactionReference.
       */
      public com.google.protobuf.ByteString
          getTransactionReferenceBytes() {
        java.lang.Object ref = transactionReference_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transactionReference_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string transaction_reference = 3;</code>
       * @param value The transactionReference to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionReference(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transactionReference_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_reference = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTransactionReference() {
        
        transactionReference_ = getDefaultInstance().getTransactionReference();
        onChanged();
        return this;
      }
      /**
       * <code>string transaction_reference = 3;</code>
       * @param value The bytes for transactionReference to set.
       * @return This builder for chaining.
       */
      public Builder setTransactionReferenceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transactionReference_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp transactionDatetime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> transactionDatetimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       * @return Whether the transactionDatetime field is set.
       */
      public boolean hasTransactionDatetime() {
        return transactionDatetimeBuilder_ != null || transactionDatetime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       * @return The transactionDatetime.
       */
      public com.google.protobuf.Timestamp getTransactionDatetime() {
        if (transactionDatetimeBuilder_ == null) {
          return transactionDatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : transactionDatetime_;
        } else {
          return transactionDatetimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      public Builder setTransactionDatetime(com.google.protobuf.Timestamp value) {
        if (transactionDatetimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactionDatetime_ = value;
          onChanged();
        } else {
          transactionDatetimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      public Builder setTransactionDatetime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (transactionDatetimeBuilder_ == null) {
          transactionDatetime_ = builderForValue.build();
          onChanged();
        } else {
          transactionDatetimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      public Builder mergeTransactionDatetime(com.google.protobuf.Timestamp value) {
        if (transactionDatetimeBuilder_ == null) {
          if (transactionDatetime_ != null) {
            transactionDatetime_ =
              com.google.protobuf.Timestamp.newBuilder(transactionDatetime_).mergeFrom(value).buildPartial();
          } else {
            transactionDatetime_ = value;
          }
          onChanged();
        } else {
          transactionDatetimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      public Builder clearTransactionDatetime() {
        if (transactionDatetimeBuilder_ == null) {
          transactionDatetime_ = null;
          onChanged();
        } else {
          transactionDatetime_ = null;
          transactionDatetimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTransactionDatetimeBuilder() {
        
        onChanged();
        return getTransactionDatetimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTransactionDatetimeOrBuilder() {
        if (transactionDatetimeBuilder_ != null) {
          return transactionDatetimeBuilder_.getMessageOrBuilder();
        } else {
          return transactionDatetime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : transactionDatetime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp transaction_datetime = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTransactionDatetimeFieldBuilder() {
        if (transactionDatetimeBuilder_ == null) {
          transactionDatetimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTransactionDatetime(),
                  getParentForChildren(),
                  isClean());
          transactionDatetime_ = null;
        }
        return transactionDatetimeBuilder_;
      }

      private double amount_ ;
      /**
       * <code>double amount = 5;</code>
       * @return The amount.
       */
      @java.lang.Override
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 5;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sparshj.Transaction)
    }

    // @@protoc_insertion_point(class_scope:sparshj.Transaction)
    private static final com.sparshj.proto.TransactionProtos.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sparshj.proto.TransactionProtos.Transaction();
    }

    public static com.sparshj.proto.TransactionProtos.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @java.lang.Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sparshj.proto.TransactionProtos.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sparshj_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sparshj_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Transaction.proto\022\007sparshj\032\037google/pro" +
      "tobuf/timestamp.proto\"\246\001\n\013Transaction\022\026\n" +
      "\016transaction_id\030\001 \001(\t\022\026\n\016account_number\030" +
      "\002 \001(\t\022\035\n\025transaction_reference\030\003 \001(\t\0228\n\024" +
      "transaction_datetime\030\004 \001(\0132\032.google.prot" +
      "obuf.Timestamp\022\016\n\006amount\030\005 \001(\001B&\n\021com.sp" +
      "arshj.protoB\021TransactionProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_sparshj_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sparshj_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sparshj_Transaction_descriptor,
        new java.lang.String[] { "TransactionId", "AccountNumber", "TransactionReference", "TransactionDatetime", "Amount", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
